---
title: Studying the relationship between environmental conditions and norovirus case
  count in the Lower Mainland
output: html_document
---

# Pre-processing and checking multicollinearity
```{r }
# load library
library(tidyverse) 
library(mice) 
library(VIM) 
library(Amelia) 
library(car) 
library(ggplot2)
library(corrplot)

# load data
cov_dat <- read.csv("Covariates data.csv")
nv_dat <- read.csv("Norovirus_data.csv")
glimpse(cov_dat)

# clean noro_count data
colnames(nv_dat) <- c("year", "epiweek", "outbreak_count")

# join tables
full_dat <- cov_dat %>%
  left_join(nv_dat, by= c("year", "epiweek"))

# multicollinearity
cov <- full_dat[,c("WDIR", "WSPD", "GSPD", "Salinity", "SST", "Total_Rain", "Mean_Temp", "Max_Temp", "Min_Temp", "Mean_Temp", "Total_Precip")]

## correlation plot
corrplot(cor(cov, use = "complete.obs"), method="circle")

## vif
model_vif <- lm(outbreak_count ~ WDIR + WSPD + GSPD + Salinity + SST + Total_Rain + Max_Temp + Min_Temp + Mean_Temp + Total_Precip, data = full_dat)
vif_values <- vif(model_vif)
vif_values

## create horizontal bar chart to display each VIF value
{par(mar=c(5,6,4,1)+.1)
  barplot(vif_values, main = "VIF Values", horiz = TRUE, col = "steelblue", xlim = c(0, 10), las=1, cex.axis = 1.3)
#add vertical line at 5
abline(v = 5, lwd = 3, lty = 2, col = "red")
}

### delete GSPD and use WSPD
### delete max/min temp and use mean temp
### delete total snow, total_precip and use total rain
### use SST


```

# mice imputations
```{r}
# check missing data type
agr_cov <- full_dat[,c("Date", "WDIR", "WSPD", "Salinity", "SST", "Total_Rain", "Mean_Temp")]
aggrP <- aggr(agr_cov, numbers=TRUE, sortVars=TRUE,cex.axis = 0.8)


# impute using mice
set.seed(123)

noro_mi <- mice(agr_cov, m=5, seed=123)


# imputed data
noro_mi1 <- complete(noro_mi, 1)
noro_mi2 <- complete(noro_mi, 2)
noro_mi3 <- complete(noro_mi, 3)
noro_mi4 <- complete(noro_mi, 4)
noro_mi5 <- complete(noro_mi, 5)

# bind into complete dataframe
no_mi_cov <- full_dat[,c("year", "epiweek")]
noro_mi1 <- cbind(noro_mi1, no_mi_cov)
noro_mi2 <- cbind(noro_mi2, no_mi_cov)
noro_mi3 <- cbind(noro_mi3, no_mi_cov)
noro_mi4 <- cbind(noro_mi4, no_mi_cov)
noro_mi5 <- cbind(noro_mi5, no_mi_cov)



# export as csv file
write.csv(noro_mi1, "data_mi1.csv")
write.csv(noro_mi2, "data_mi2.csv")
write.csv(noro_mi3, "data_mi3.csv")
write.csv(noro_mi4, "data_mi4.csv")
write.csv(noro_mi5, "data_mi5.csv")



```



```{r}
# plots
library("imputeTS")

ggplot_na_imputations(full_dat$Mean_Temp, noro_mi1$Mean_Temp, ylab = "Mean Temperature", title = "", legend = FALSE)
ggplot_na_imputations(full_dat$SST, noro_mi1$SST, ylab = "SST", title = "", legend = FALSE)

```

# Evaluating performance of imputation methods

```{r}
set.seed(123)
# randomly sample 10% of available data for each variable
rm_wdir <- round((dim(full_dat)[1] - sum(is.na(agr_cov$WDIR)))*0.1)
rm_wspd <- round((dim(full_dat)[1] - sum(is.na(agr_cov$WSPD)))*0.1)
rm_sal <- round((dim(full_dat)[1] - sum(is.na(agr_cov$Salinity)))*0.1)
rm_sst <- round((dim(full_dat)[1] - sum(is.na(agr_cov$SST)))*0.1)
rm_tr <- round((dim(full_dat)[1] - sum(is.na(agr_cov$Total_Rain)))*0.1)
rm_mt <- round((dim(full_dat)[1] - sum(is.na(agr_cov$Mean_Temp)))*0.1)

na_ind_wdir <- sample(which(!is.na(full_dat$WDIR)), rm_wdir)
na_ind_wspd <- sample(which(!is.na(full_dat$WSPD)), rm_wspd)
na_ind_sal <- sample(which(!is.na(full_dat$Salinity)), rm_sal)
na_ind_sst <- sample(which(!is.na(full_dat$SST)), rm_sst)
na_ind_tr <- sample(which(!is.na(full_dat$Total_Rain)), rm_tr)
na_ind_mt <- sample(which(!is.na(full_dat$Mean_Temp)), rm_mt)

na_wdir <- replace(agr_cov$WDIR, na_ind_wdir, NA)
na_wspd <- replace(agr_cov$WSPD, na_ind_wspd, NA)
na_sal <- replace(agr_cov$Salinity, na_ind_sal, NA)
na_sst <- replace(agr_cov$SST, na_ind_sst, NA)
na_tr <- replace(agr_cov$Total_Rain, na_ind_tr, NA)
na_mt <- replace(agr_cov$Mean_Temp, na_ind_mt, NA)
Date<- agr_cov$Date

na_df <- cbind(na_wdir, na_wspd, na_sal, na_sst, na_tr, na_mt)


# mice imputation for each variable with 10% NA 
na_noro_mi <- mice(na_df, m=5, seed=123)

# imputed data
na_noro_mi1 <- complete(na_noro_mi, 1)
na_noro_mi2 <- complete(na_noro_mi, 2)
na_noro_mi3 <- complete(na_noro_mi, 3)
na_noro_mi4 <- complete(na_noro_mi, 4)
na_noro_mi5 <- complete(na_noro_mi, 5)

# imputed data only where 10% NA filled
na_wdir_mi1 <- na_noro_mi1$na_wdir[c(na_ind_wdir)]
na_wdir_mi2 <- na_noro_mi2$na_wdir[c(na_ind_wdir)]
na_wdir_mi3 <- na_noro_mi3$na_wdir[c(na_ind_wdir)]
na_wdir_mi4 <- na_noro_mi4$na_wdir[c(na_ind_wdir)]
na_wdir_mi5 <- na_noro_mi5$na_wdir[c(na_ind_wdir)]

na_wspd_mi1 <- na_noro_mi1$na_wspd[c(na_ind_wspd)]
na_wspd_mi2 <- na_noro_mi2$na_wspd[c(na_ind_wspd)]
na_wspd_mi3 <- na_noro_mi3$na_wspd[c(na_ind_wspd)]
na_wspd_mi4 <- na_noro_mi4$na_wspd[c(na_ind_wspd)]
na_wspd_mi5 <- na_noro_mi5$na_wspd[c(na_ind_wspd)]

na_sal_mi1 <- na_noro_mi1$na_sal[c(na_ind_sal)]
na_sal_mi2 <- na_noro_mi2$na_sal[c(na_ind_sal)]
na_sal_mi3 <- na_noro_mi3$na_sal[c(na_ind_sal)]
na_sal_mi4 <- na_noro_mi4$na_sal[c(na_ind_sal)]
na_sal_mi5 <- na_noro_mi5$na_sal[c(na_ind_sal)]

na_sst_mi1 <- na_noro_mi1$na_sst[c(na_ind_sst)]
na_sst_mi2 <- na_noro_mi2$na_sst[c(na_ind_sst)]
na_sst_mi3 <- na_noro_mi3$na_sst[c(na_ind_sst)]
na_sst_mi4 <- na_noro_mi4$na_sst[c(na_ind_sst)]
na_sst_mi5 <- na_noro_mi5$na_sst[c(na_ind_sst)]

na_tr_mi1 <- na_noro_mi1$na_tr[c(na_ind_tr)]
na_tr_mi2 <- na_noro_mi2$na_tr[c(na_ind_tr)]
na_tr_mi3 <- na_noro_mi3$na_tr[c(na_ind_tr)]
na_tr_mi4 <- na_noro_mi4$na_tr[c(na_ind_tr)]
na_tr_mi5 <- na_noro_mi5$na_tr[c(na_ind_tr)]

na_mt_mi1 <- na_noro_mi1$na_mt[c(na_ind_mt)]
na_mt_mi2 <- na_noro_mi2$na_mt[c(na_ind_mt)]
na_mt_mi3 <- na_noro_mi3$na_mt[c(na_ind_mt)]
na_mt_mi4 <- na_noro_mi4$na_mt[c(na_ind_mt)]
na_mt_mi5 <- na_noro_mi5$na_mt[c(na_ind_mt)]

# rmse for each imputation
# rmse = sqrt(mean(observed - predicted)^2))
library(Metrics)
rmse_wdir_mi1 <- rmse(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi1)
rmse_wdir_mi2 <- rmse(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi2)
rmse_wdir_mi3 <- rmse(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi3)
rmse_wdir_mi4 <- rmse(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi4)
rmse_wdir_mi5 <- rmse(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi5)

rmse_wspd_mi1 <- rmse(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi1)
rmse_wspd_mi2 <- rmse(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi2)
rmse_wspd_mi3 <- rmse(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi3)
rmse_wspd_mi4 <- rmse(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi4)
rmse_wspd_mi5 <- rmse(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi5)

rmse_sal_mi1 <- rmse(agr_cov$Salinity[c(na_ind_sal)], na_sal_mi1)
rmse_sal_mi2 <- rmse(agr_cov$Salinity[c(na_ind_sal)], na_sal_mi2)
rmse_sal_mi3 <- rmse(agr_cov$Salinity[c(na_ind_sal)], na_sal_mi3)
rmse_sal_mi4 <- rmse(agr_cov$Salinity[c(na_ind_sal)], na_sal_mi4)
rmse_sal_mi5 <- rmse(agr_cov$Salinity[c(na_ind_sal)], na_sal_mi5)

rmse_sst_mi1 <- rmse(agr_cov$SST[c(na_ind_sst)], na_sst_mi1)
rmse_sst_mi2 <- rmse(agr_cov$SST[c(na_ind_sst)], na_sst_mi2)
rmse_sst_mi3 <- rmse(agr_cov$SST[c(na_ind_sst)], na_sst_mi3)
rmse_sst_mi4 <- rmse(agr_cov$SST[c(na_ind_sst)], na_sst_mi4)
rmse_sst_mi5 <- rmse(agr_cov$SST[c(na_ind_sst)], na_sst_mi5)

rmse_tr_mi1 <- rmse(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi1)
rmse_tr_mi2 <- rmse(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi2)
rmse_tr_mi3 <- rmse(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi3)
rmse_tr_mi4 <- rmse(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi4)
rmse_tr_mi5 <- rmse(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi5)

rmse_mt_mi1 <- rmse(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi1)
rmse_mt_mi2 <- rmse(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi2)
rmse_mt_mi3 <- rmse(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi3)
rmse_mt_mi4 <- rmse(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi4)
rmse_mt_mi5 <- rmse(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi5)


# bias for each imputation
## bias = mean(observed - predicted)
bias_wdir_mi1 <- bias(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi1)
bias_wdir_mi2 <- bias(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi2)
bias_wdir_mi3 <- bias(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi3)
bias_wdir_mi4 <- bias(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi4)
bias_wdir_mi5 <- bias(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi5)

bias_wspd_mi1 <- bias(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi1)
bias_wspd_mi2 <- bias(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi2)
bias_wspd_mi3 <- bias(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi3)
bias_wspd_mi4 <- bias(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi4)
bias_wspd_mi5 <- bias(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi5)

bias_sal_mi1 <- bias(agr_cov$SAL[c(na_ind_sal)], na_sal_mi1)
bias_sal_mi2 <- bias(agr_cov$SAL[c(na_ind_sal)], na_sal_mi2)
bias_sal_mi3 <- bias(agr_cov$SAL[c(na_ind_sal)], na_sal_mi3)
bias_sal_mi4 <- bias(agr_cov$SAL[c(na_ind_sal)], na_sal_mi4)
bias_sal_mi5 <- bias(agr_cov$SAL[c(na_ind_sal)], na_sal_mi5)

bias_sst_mi1 <- bias(agr_cov$SST[c(na_ind_sst)], na_sst_mi1)
bias_sst_mi2 <- bias(agr_cov$SST[c(na_ind_sst)], na_sst_mi2)
bias_sst_mi3 <- bias(agr_cov$SST[c(na_ind_sst)], na_sst_mi3)
bias_sst_mi4 <- bias(agr_cov$SST[c(na_ind_sst)], na_sst_mi4)
bias_sst_mi5 <- bias(agr_cov$SST[c(na_ind_sst)], na_sst_mi5)

bias_tr_mi1 <- bias(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi1)
bias_tr_mi2 <- bias(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi2)
bias_tr_mi3 <- bias(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi3)
bias_tr_mi4 <- bias(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi4)
bias_tr_mi5 <- bias(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi5)

bias_mt_mi1 <- bias(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi1)
bias_mt_mi2 <- bias(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi2)
bias_mt_mi3 <- bias(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi3)
bias_mt_mi4 <- bias(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi4)
bias_mt_mi5 <- bias(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi5)

```
## Amelia 
```{r}
set.seed(123)
# mice imputation for each variable with 10% NA 

data_impute <- data.frame(na_wdir, na_wspd, na_sal, na_sst, na_tr, na_mt, Date)


a.out<-amelia(data_impute,ts=" Date")


# imputed data

imp1<-a.out$imputations[[1]]
imp2<-a.out$imputations[[2]]
imp3<-a.out$imputations[[3]]
imp4<-a.out$imputations[[4]]
imp5<-a.out$imputations[[5]]


# imputed data only where 10% NA filled
na_wdir_mi1 <- imp1$na_wdir[c(na_ind_wdir)]
na_wdir_mi2 <- imp2$na_wdir[c(na_ind_wdir)]
na_wdir_mi3 <- imp3$na_wdir[c(na_ind_wdir)]
na_wdir_mi4 <- imp4$na_wdir[c(na_ind_wdir)]
na_wdir_mi5 <- imp5$na_wdir[c(na_ind_wdir)]

na_wspd_mi1 <- imp1$na_wspd[c(na_ind_wspd)]
na_wspd_mi2 <- imp2$na_wspd[c(na_ind_wspd)]
na_wspd_mi3 <- imp3$na_wspd[c(na_ind_wspd)]
na_wspd_mi4 <- imp4$na_wspd[c(na_ind_wspd)]
na_wspd_mi5 <- imp5$na_wspd[c(na_ind_wspd)]

na_sal_mi1 <- imp1$na_sal[c(na_ind_sal)]
na_sal_mi2 <- imp2$na_sal[c(na_ind_sal)]
na_sal_mi3 <- imp3$na_sal[c(na_ind_sal)]
na_sal_mi4 <- imp4$na_sal[c(na_ind_sal)]
na_sal_mi5 <- imp5$na_sal[c(na_ind_sal)]

na_sst_mi1 <- imp1$na_sst[c(na_ind_sst)]
na_sst_mi2 <- imp2$na_sst[c(na_ind_sst)]
na_sst_mi3 <- imp3$na_sst[c(na_ind_sst)]
na_sst_mi4 <- imp4$na_sst[c(na_ind_sst)]
na_sst_mi5 <- imp5$na_sst[c(na_ind_sst)]

na_tr_mi1 <- imp1$na_tr[c(na_ind_tr)]
na_tr_mi2 <- imp2$na_tr[c(na_ind_tr)]
na_tr_mi3 <- imp3$na_tr[c(na_ind_tr)]
na_tr_mi4 <- imp4$na_tr[c(na_ind_tr)]
na_tr_mi5 <- imp5$na_tr[c(na_ind_tr)]

na_mt_mi1 <- imp1$na_mt[c(na_ind_mt)]
na_mt_mi2 <- imp2$na_mt[c(na_ind_mt)]
na_mt_mi3 <- imp3$na_mt[c(na_ind_mt)]
na_mt_mi4 <- imp4$na_mt[c(na_ind_mt)]
na_mt_mi5 <- imp5$na_mt[c(na_ind_mt)]
```

```{r}
# rmse for each imputation
# rmse = sqrt(mean(observed - predicted)^2))
library(Metrics)
rmse_wdir_am1 <- rmse(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi1)
rmse_wdir_am2 <- rmse(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi2)
rmse_wdir_am3 <- rmse(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi3)
rmse_wdir_am4 <- rmse(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi4)
rmse_wdir_am5 <- rmse(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi5)

rmse_wspd_am1 <- rmse(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi1)
rmse_wspd_am2 <- rmse(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi2)
rmse_wspd_am3 <- rmse(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi3)
rmse_wspd_am4 <- rmse(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi4)
rmse_wspd_am5 <- rmse(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi5)

rmse_sal_am1 <- rmse(agr_cov$Salinity[c(na_ind_sal)], na_sal_mi1)
rmse_sal_am2 <- rmse(agr_cov$Salinity[c(na_ind_sal)], na_sal_mi2)
rmse_sal_am3 <- rmse(agr_cov$Salinity[c(na_ind_sal)], na_sal_mi3)
rmse_sal_am4 <- rmse(agr_cov$Salinity[c(na_ind_sal)], na_sal_mi4)
rmse_sal_am5 <- rmse(agr_cov$Salinity[c(na_ind_sal)], na_sal_mi5)

rmse_sst_am1 <- rmse(agr_cov$SST[c(na_ind_sst)], na_sst_mi1)
rmse_sst_am2 <- rmse(agr_cov$SST[c(na_ind_sst)], na_sst_mi2)
rmse_sst_am3 <- rmse(agr_cov$SST[c(na_ind_sst)], na_sst_mi3)
rmse_sst_am4 <- rmse(agr_cov$SST[c(na_ind_sst)], na_sst_mi4)
rmse_sst_am5 <- rmse(agr_cov$SST[c(na_ind_sst)], na_sst_mi5)

rmse_tr_am1 <- rmse(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi1)
rmse_tr_am2 <- rmse(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi2)
rmse_tr_am3 <- rmse(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi3)
rmse_tr_am4 <- rmse(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi4)
rmse_tr_am5 <- rmse(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi5)

rmse_mt_am1 <- rmse(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi1)
rmse_mt_am2 <- rmse(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi2)
rmse_mt_am3 <- rmse(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi3)
rmse_mt_am4 <- rmse(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi4)
rmse_mt_am5 <- rmse(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi5)


# bias for each imputation
## bias = mean(observed - predicted)
bias_wdir_am1 <- bias(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi1)
bias_wdir_am2 <- bias(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi2)
bias_wdir_am3 <- bias(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi3)
bias_wdir_am4 <- bias(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi4)
bias_wdir_am5 <- bias(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_mi5)

bias_wspd_am1 <- bias(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi1)
bias_wspd_am2 <- bias(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi2)
bias_wspd_am3 <- bias(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi3)
bias_wspd_am4 <- bias(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi4)
bias_wspd_am5 <- bias(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_mi5)

bias_sal_am1 <- bias(agr_cov$SAL[c(na_ind_sal)], na_sal_mi1)
bias_sal_am2 <- bias(agr_cov$SAL[c(na_ind_sal)], na_sal_mi2)
bias_sal_am3 <- bias(agr_cov$SAL[c(na_ind_sal)], na_sal_mi3)
bias_sal_am4 <- bias(agr_cov$SAL[c(na_ind_sal)], na_sal_mi4)
bias_sal_am5 <- bias(agr_cov$SAL[c(na_ind_sal)], na_sal_mi5)

bias_sst_am1 <- bias(agr_cov$SST[c(na_ind_sst)], na_sst_mi1)
bias_sst_am2 <- bias(agr_cov$SST[c(na_ind_sst)], na_sst_mi2)
bias_sst_am3 <- bias(agr_cov$SST[c(na_ind_sst)], na_sst_mi3)
bias_sst_am4 <- bias(agr_cov$SST[c(na_ind_sst)], na_sst_mi4)
bias_sst_am5 <- bias(agr_cov$SST[c(na_ind_sst)], na_sst_mi5)

bias_tr_am1 <- bias(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi1)
bias_tr_am2 <- bias(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi2)
bias_tr_am3 <- bias(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi3)
bias_tr_am4 <- bias(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi4)
bias_tr_am5 <- bias(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_mi5)

bias_mt_am1 <- bias(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi1)
bias_mt_am2 <- bias(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi2)
bias_mt_am3 <- bias(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi3)
bias_mt_am4 <- bias(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi4)
bias_mt_am5 <- bias(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_mi5)

```


## TS imputation
```{r}
WDIR<- na_kalman(data_impute$na_wdir)
WSPD<- na_kalman(data_impute$na_wspd)
Salinity<- na_kalman(data_impute$na_sal)
SST<- na_kalman(data_impute$na_sst)
Mean_Temp<- na_kalman(data_impute$na_mt)
Total_Rain<- na_kalman(data_impute$na_tr)

# imputed data only where 10% NA filled
na_wdir_ts <- na_noro_mi1$na_wdir[c(na_ind_wdir)]

na_wspd_ts <- na_noro_mi1$na_wspd[c(na_ind_wspd)]

na_sal_ts <- na_noro_mi1$na_sal[c(na_ind_sal)]

na_sst_ts <- na_noro_mi1$na_sst[c(na_ind_sst)]

na_tr_ts <- na_noro_mi1$na_tr[c(na_ind_tr)]

na_mt_ts <- na_noro_mi1$na_mt[c(na_ind_mt)]

rmse_wdir_ts <- rmse(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_ts)
rmse_wspd_ts <- rmse(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_ts)
rmse_sal_ts <- rmse(agr_cov$Salinity[c(na_ind_sal)], na_sal_ts)
rmse_sst_ts <- rmse(agr_cov$SST[c(na_ind_sst)], na_sst_ts)
rmse_tr_ts <- rmse(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_ts)
rmse_mt_ts <- rmse(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_ts)


bias_wdir_ts <- bias(agr_cov$WDIR[c(na_ind_wdir)], na_wdir_ts)
bias_wspd_ts <- bias(agr_cov$WSPD[c(na_ind_wspd)], na_wspd_ts)


bias_sal_ts <- bias(agr_cov$SAL[c(na_ind_sal)], na_sal_ts)


bias_sst_ts <- bias(agr_cov$SST[c(na_ind_sst)], na_sst_ts)


bias_tr_ts <- bias(agr_cov$Total_Rain[c(na_ind_tr)], na_tr_ts)


bias_mt_ts <- bias(agr_cov$Mean_Temp[c(na_ind_mt)], na_mt_ts)


```


